name: TWS CI workflow

#yeh tb run hoga j developer code push karega ya pull request banayega main branch me
on:
    push:

jobs:
    build: #job ka name h
        runs-on: ubuntu-latest #github runner which are free to use and have all the necessary tools pre-installed
        steps:
            - name: Checkout code #step ka name h
              uses: actions/checkout@v4 #clone the code into a ubuntu runner
           
            - name: Setup Docker
              uses: docker/setup-buildx-action@v4 #setup docker buildx which is a tool for building multi-platform docker images

            